version: "3"
services:
  serverless:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/var/task
      - gem_data:/usr/local/bundle
    env_file:
      - docker.env
    tty: true
    ports:
      - 3000:3000
    entrypoint:
      - sh
    command:
      - -c
      - bundle install && sls offline --host 0.0.0.0
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb_local
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data # 永続化するデータのファイルパス
    volumes:
      - ./dynamodb_data:/data # データの永続化
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
  awscli:
    image: "amazon/aws-cli"
    entrypoint:
      - sh
    tty: true
    volumes:
      - ./dynamodb_shell:/aws
    environment:
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DYNAMODB_REGION: ap-northeast-1
    depends_on:
      - dynamodb-local
volumes:
  gem_data:
