service: lambda-dynamodb-serverless
frameworkVersion: "3"
provider:
  name: aws
  runtime: ruby2.7
  region: ap-northeast-1
  lambdaHashingVersion: 20201221
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
plugins:
  - serverless-offline
